version: '3.8'

services:
  mysql-db:
    image: mysql
    container_name: bookDB
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
